django_learn_helper/urls.py
from django.contrib import admin
from django.urls import path, include
from words import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('words/', include('words.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path('__debug__/', include('debug_toolbar.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

words/urls.py
from django.urls import path
from . import views
from .views import tests_views, words_views, groups_views

app_name = 'words'

urlpatterns = [
    path('list/', words_views.WordsListView.as_view(), name="list"),
    # path('add/', words_views.add_view),
    # path('test/', views.test_view),
    path('', words_views.home_view, name="home"),
    path('<uuid:uuid>/', words_views.one_word_view, name="single"),
    path("create/", words_views.WordCreateView.as_view(), name="create"),
    path("update/<uuid:uuid>/", words_views.WordUpdateView.as_view(), name="update"),
    path("delete/<uuid:uuid>/", words_views.delete_view, name="delete"),
    path("groups/", groups_views.GroupsListView.as_view(), name="groups_list"),
    path("groups/<uuid:uuid>", groups_views.WordsInGroupListView.as_view(), name='group'),
    path("groups/create", groups_views.GroupCreateView.as_view(), name="group_create"),
    path("groups/update/<uuid:uuid>", groups_views.GroupUpdateView.as_view(), name="group_update"),
    path("tests", tests_views.TestsHomeView.as_view(), name="tests_home"),
    # path("tests/quick_test", views.QuickTest.as_view(), name="quick_test"),
    path("tests/groups_of_words_test/<uuid:uuid>", tests_views.GroupOfWordsTest.as_view(), name="groups_of_words_test"),
    path("tests/group_of_words_test/results", tests_views.TestsResultsListView.as_view(), name="test_results"),
    path("tests/group_of_words_test/results/<uuid:uuid>", tests_views.TestsResultView.as_view(), name="single_result")
]

words/views/groups_views.py
import random

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic.detail import SingleObjectMixin, DetailView

from words.filters import WordFilter
from words.models import Word, GroupOfWords, Result

from words.forms import WordForm, GroupForm, GroupFilterForm, GroupChoiceForm, TestInputForm, TestParametersForm
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, TemplateView
from django.views.generic.edit import ProcessFormView, UpdateView, DeleteView, FormView


class GroupsListView(ListView):
    template_name = "words/groups_List.html"
    model = GroupOfWords
    context_object_name = 'groups'

    def get_queryset(self):
        super(GroupsListView, self).get_queryset()
        return self.request.user.groups_of_words.all()

    def post(self, request):
        checks = request.POST.getlist("checks[]")
        for idi in checks:
            group = GroupOfWords.objects.get(id=idi)
            if group.name == "General":
                return HttpResponseRedirect(reverse_lazy("words:home"))
            group.delete()
        return redirect(reverse_lazy("words:groups_list"))


class GroupCreateView(FormView):
    model = GroupOfWords
    template_name = "words/group_form.html"
    form_class = GroupForm
    success_url = reverse_lazy("words:groups_list")

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""
        kwargs = super(GroupCreateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        super().form_valid(self)
        group_obj = form.instance
        words = form.cleaned_data['words']
        group_obj.user = self.request.user
        group_obj.save()
        for word in words:
            group_obj.words.add(word)
        group_obj.save()

        return HttpResponseRedirect(reverse_lazy("words:groups_list"))


class GroupUpdateView(FormView):
    template_name = "words/group_form.html"
    form_class = GroupForm
    success_url = reverse_lazy("words:groups_list")
    pk_url_kwarg = "uuid"

    def get(self, request, *args, **kwargs):
        uuid = self.kwargs.get('uuid')
        group_obj = GroupOfWords.objects.get(id=uuid)
        if group_obj.name == "General":
            return HttpResponseRedirect(reverse_lazy("words:home"))
        return super().get(self, request, *args, **kwargs)

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""
        kwargs = super(GroupUpdateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        uuid = self.kwargs.get('uuid')
        group_obj = GroupOfWords.objects.get(id=uuid)
        initial['words'] = group_obj.words.all()
        initial["name"] = group_obj.name
        initial["description"] = group_obj.description
        return initial

    def form_valid(self, form):
        super().form_valid(self)
        words = form.cleaned_data['words']
        uuid = self.kwargs.get('uuid')
        group_obj = GroupOfWords.objects.get(id=uuid)
        group_obj.words.clear()
        for word in words:
            group_obj.words.add(word)
        group_obj.description = form.cleaned_data["description"]
        group_obj.name = form.cleaned_data["name"]
        group_obj.save()

        return HttpResponseRedirect(reverse_lazy("words:groups_list"))


class WordsInGroupListView(ListView):
    model = Word
    context_object_name = "words"
    pk_url_kwarg = 'uuid'

    def get_queryset(self):
        super(WordsInGroupListView, self).get_queryset()
        uuid = self.kwargs.get("uuid")
        return GroupOfWords.objects.get(id=uuid).words.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        uuid = self.kwargs.get("uuid")
        context["group_obj"] = GroupOfWords.objects.get(id=uuid)
        return context

    def get_template_names(self):
        super().get_template_names()
        if not self.request.user.words.all():
            return ["words/no_words.html"]
        else:
            return ["words/words_in_group_list.html"]


def add_view(request):
    return render(request, "words/no_words.html")


def test_view(request):
    return render(request, "words/test.html")

words/views/tests_views.py
import random

from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic.detail import DetailView

from words.models import Word, GroupOfWords, Result

from words.forms import TestInputForm, TestParametersForm

from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import FormView


def create_result_json(list_of_uuids):
    json = {"test_words": {}}
    for uuid in list_of_uuids:
        json["test_words"][f"{uuid}"] = {"input_word": None, "is_correct": None}
    return json


class TestsHomeView(TemplateView):
    template_name = "tests/tests_home.html"

    def get_context_data(self, **kwargs):
        context = super(TestsHomeView, self).get_context_data(**kwargs)
        context["form"] = TestParametersForm(self.request.user)
        return context

    def post(self, request):
        uuid = self.request.POST.getlist("groups")[0]
        kwargs = {'uuid': uuid}
        request.session['test_params'] = {}

        if request.POST.getlist("durations")[0] == "finite":
            request.session['test_params']["duration"] = "finite"
            words_qs = GroupOfWords.objects.get(id=uuid).words.all()
            list_test_words = [str(word.id) for word in words_qs]
            request.session['test_params']["list_test_words"] = list_test_words
            result = Result.objects.create(user=request.user, details=create_result_json(list_test_words))
            result.save()
            request.session["test_params"]["result_id"] = str(result.id)
        elif request.POST.getlist("durations")[0] == "loop":
            request.session['test_params']['duration'] = "loop"

        if request.POST.getlist("type")[0] == "ranked":
            request.session['test_params']["test_eval"] = "ranked"
        elif request.POST.getlist("type")[0] == "unranked":
            request.session['test_params']["test_eval"] = "unranked"

        if request.POST.getlist("test_for_translation_of")[0] == "for_w1":
            request.session["test_params"]["for_wX"] = 1
        elif request.POST.getlist("test_for_translation_of")[0] == "for_w2":
            request.session["test_params"]["for_wX"] = 2

        if request.POST.getlist("do_with_incorrect")[0] == "skip":
            request.session["test_params"]["do_with_incorrect"] = "skip"
        elif request.POST.getlist("do_with_incorrect")[0] == "repeat":
            request.session["test_params"]["do_with_incorrect"] = "repeat"

        if request.POST.getlist("lower_score_first")[0] == "lower_score_first":
            request.session["test_params"]["lower_score_first"] = "lower_score_first"
        elif request.POST.getlist("lower_score_first")[0] == "random_score_first":
            request.session["test_params"]["lower_score_first"] = "random_score_first"

        request.session['test_params']["is_ended"] = False
        request.session.modified = True
        return redirect(
            reverse_lazy("words:groups_of_words_test", kwargs=kwargs))


class GroupOfWordsTest(FormView):
    pk_url_kwarg = "uuid"
    template_name = "tests/quick_test.html"
    form_class = TestInputForm
    model = Word
    success_url = reverse_lazy("words:list")

    def get(self, request, *args, **kwargs):
        try:
            var = request.session["test_params"]
        except KeyError:
            return redirect(reverse_lazy("words:tests_home"))
        try:
            if not request.session["test_params"]['list_test_words']:
                uuid = request.session["test_params"]["result_id"]
                del request.session["test_params"]
                return redirect(reverse_lazy("words:single_result", kwargs={"uuid": uuid}))
        except KeyError:
            pass

        return self.render_to_response(self.get_context_data(req=request))

    def get_context_data(self, **kwargs):
        request = kwargs["req"]
        context = super().get_context_data(**kwargs)

        print(request.session["test_params"])

        if request.session["test_params"]["for_wX"] == 1:
            context["for_wX"] = 1
        elif request.session["test_params"]["for_wX"] == 2:
            context["for_wX"] = 2

        if request.session["test_params"]["duration"] == "finite":
            context["group_obj"] = GroupOfWords.objects.get(id=self.kwargs.get("uuid"))
            randint = random.randint(0, len(request.session["test_params"]["list_test_words"]) - 1)
            print('\n', request.session["test_params"]["list_test_words"], "\n")
            random_word_id = request.session["test_params"]["list_test_words"].pop(randint)
            request.session.modified = True
            print('\n', request.session["test_params"]["list_test_words"], "\n")
            context["word_obj"] = Word.objects.get(id=random_word_id)
            return context

        elif request.session["test_params"]["duration"] == "loop":
            context["group_obj"] = GroupOfWords.objects.get(id=self.kwargs.get("uuid"))
            if request.session["test_params"]["lower_score_first"] == "lower_score_first":
                min_score = context["group_obj"].words.filter().order_by('score').first().score
                context["word_obj"] = random.choice(context["group_obj"].words.filter(score=min_score))
            else:
                context["word_obj"] = random.choice(context["group_obj"].words.filter().order_by('score').first())
            return context

    def form_valid(self, form):
        if form.is_valid():
            word_obj = Word.objects.get(id=self.request.POST.getlist("word_obj")[0])
            input_word = self.request.POST.getlist("input_word")[0].lower().strip(" ")
            compare_with = None
            try:
                if self.request.session["test_params"]["for_wX"] == 1:
                    compare_with = word_obj.word2.lower().strip(" ")
                elif self.request.session["test_params"]["for_wX"] == 2:
                    compare_with = word_obj.word1.lower().strip(" ")
            except KeyError:
                return redirect(reverse_lazy("words:tests_home"))
            print(f"\nI COMPARE {compare_with} WITH {input_word}\n")

            if compare_with == input_word:
                messages.success(self.request,
                                 f'Answer "{input_word}" is correct. Translation of "{word_obj.word1}" is '
                                 f'"{word_obj.word2}"')
                if self.request.session["test_params"]["test_eval"] == "ranked":
                    word_obj.score += 1
                if self.request.session["test_params"]["duration"] == "finite":
                    res_obj = Result.objects.get(id=self.request.session["test_params"]["result_id"])
                    res_obj.details["test_words"][f"{str(word_obj.id)}"]["input_word"] = input_word
                    res_obj.details["test_words"][f"{str(word_obj.id)}"]["is_correct"] = True
                    res_obj.save()

            elif compare_with != input_word:
                messages.success(self.request,
                                 f'Answer "{input_word}" is incorrect. Correct translation of "{word_obj.word1}" is '
                                 f'"{word_obj.word2}"')

                if self.request.session["test_params"]["test_eval"] == "ranked":
                    word_obj.score -= 1
                if self.request.session["test_params"]["do_with_incorrect"] == "repeat" and \
                        self.request.session["test_params"]["duration"] == "finite":
                    self.request.session["test_params"]["list_test_words"].append(str(word_obj.id))
                    self.request.session.modified = True
                if self.request.session["test_params"]["duration"] == "finite":
                    res_obj = Result.objects.get(id=self.request.session["test_params"]["result_id"])
                    res_obj.details["test_words"][f"{str(word_obj.id)}"]["input_word"] = input_word
                    res_obj.details["test_words"][f"{str(word_obj.id)}"]["is_correct"] = False
                    res_obj.save()

            word_obj.save()

            return redirect(
                reverse_lazy(f"words:groups_of_words_test", kwargs={'uuid': self.kwargs["uuid"]}))


class TestsResultsListView(ListView):
    model = Result
    context_object_name = 'results'
    template_name = "tests/results_list.html"

    def get_queryset(self):
        super(TestsResultsListView, self).get_queryset()
        print(self.request.user.results)
        return self.request.user.results.all()

    def get(self, request, *args, **kwargs):
        return super(TestsResultsListView, self).get(request, *args, **kwargs)

def update_result_details():
    pass

class TestsResultView(DetailView):
    pk_url_kwarg = "uuid"
    model = Result
    context_object_name = "result"
    template_name = "tests/single_result.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        res_obj = Result.objects.get(id=self.kwargs["uuid"])
        context_dict = res_obj.generate_context_dict()
        context["dict"] = context_dict
        return context

words/templates/words/delete.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="POST">
      {% csrf_token %}
    <p>U sure? {{word}}</p>
    <a href="{% url 'words:list' %}"> Go back </a>
        <input type="submit" value="Confirm"/>

</form>

{% endblock %}

words/templates/words/group_form.html
{% extends 'base.html' %}

{% block content %}

<h1>Group creation/updation</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{% endblock %}

words/templates/words/groups_list.html
{% extends 'base.html' %}


{% block content %}
<form action="" method="POST">
    {% csrf_token %}

    <table>
        <tr>
            <th>Name</th>
            <th>View</th>
            <th>Update</th>
            <th>Checkbox</th>
        </tr>
        {% for group in groups %}

        <tr>
            <td>{{group.name}}</td>
            <td><a href="{% url 'words:group' uuid=group.id %}">View</a></td>
            {% if group.name != "General" %}
            <td><a href="{% url 'words:group_update' uuid=group.id %}">Update</a></td>
            <td><input type="Checkbox" name="checks[]" value="{{group.id}}"></td>
            {% endif %}
        </tr>

        {% endfor %}
    </table>

    <hr>

    <input type="Submit" value="Delete" name="delete_button">

    <a href="{% url 'words:group_create' %}">Create</a>

</form>


{% endblock %}

words/templates/words/home.html
{% extends 'base.html' %}

{% block content %}


<h1>Welcome to home page of words!!!</h1>

<table>
    <tr>
        <td><h1><a href="{% url 'words:list' %}">Words list</a></h1></td>
        <td><a href="{% url 'words:create' %}"><h1>Create a word</h1></a></td>
        <td><a href="{% url 'words:groups_list' %}"><h1>Group list</h1></a></td>
        <td><a href="{% url 'words:group_create' %}"><h1>Create a group</h1></a></td>
        <td><a href="{% url 'words:tests_home'%}"><h1>Tests</h1></a></td>
    </tr>
</table>

{% endblock content %}

words/templates/words/list.html
{% extends 'base.html' %}
{% load static%}
<h1>List</h1>


{% block content %}

<img src="{% static 'words/baba.jpg' %}" width="50" height="50">

<form action="" method="GET">
    {{ filter.form }}
    <input type="Submit" name="filter_button" value="Search">
    <input type="Reset" value="Reset">
</form>

<a href="{% url 'words:list' %}">Reset filter</a>

<hr>

<ul>
    <li>AVG: {{ avg }}</li>
    <li> MAX: {{ max }}</li>
    <li> MIN {{ min }}</li>
</ul>


<hr>
<form action="" method="POST">
    <a href="{% url 'words:create' %}">Create</a>
    {% csrf_token %}
    <input type="Submit" name="delete_button" value="Delete">

    <table>
        <tr>
            <th>Word</th>
            <th>Translation</th>
            <th>Score</th>
            <th>View</th>
            <th>Update</th>
            <th></th>
            <th>Checkbox</th>
        </tr>

        {% if user.is_authenticated %}


        {% for word in filter.qs %}
        <tr>
            <td>{{word.word1}}</td>
            <td>{{word.word2}}</td>
            <td>{{word.score}}</td>
            <td><a href="{% url 'words:single' uuid=word.id %}">View</a></td>
            <td><a href="{% url 'words:update' uuid=word.id %}">Update</a></td>
            <td><a href="{% url 'words:delete' uuid=word.id %}">Delete</a></td>
            <td><input type="Checkbox" name="checks" value="{{word.id}}"></td>
        <tr>
            {% endfor %}

            {% endif %}

    </table>
</form>



{% endblock content %}

words/templates/words/no_words.html
{% extends 'base.html' %}

{% block content %}
<h1>U dont have words yet</h1>
<a href="{% url 'words:create' %}">Create a word</a>
{% endblock content %}

words/templates/words/single_word.html
{% extends 'base.html' %}

{% block content %}
<h1>SINGLE WORD</h1>
<h1>{{word.word1}} - {{word.word2}}</h1>
{% endblock content %}

words/templates/words/word_form.html
{% extends 'base.html' %}

{% block content %}

<h1>Word creation</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

<a href="{% url 'words:list' %}">Words list</a>
{% endblock %}

words/templates/words/word_update.html
{% extends 'base.html' %}

{% block content %}

<h1>Word creation</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{% endblock %}

words/templates/words/words_in_group_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Group of words: {{group_obj.name}}</h1>
<a href="{% url 'words:group_update' uuid=group_obj.id %}">Update group</a>
<table>
    <tr>
        <th>Word</th>
        <th>Translation</th>
        <th>Score</th>
        <th>View</th>
        <th>Update</th>
        <th></th>
        <th>Checkbox</th>
    </tr>

    {% if user.is_authenticated %}


    {% for word in words %}
    <tr>
        <td>{{word.word1}}</td>
        <td>{{word.word2}}</td>
        <td>{{word.score}}</td>
        <td><a href="{% url 'words:single' uuid=word.id %}">View</a></td>
        <td><a href="{% url 'words:update' uuid=word.id %}">Update</a></td>
        <td><a href="{% url 'words:delete' uuid=word.id %}">Delete</a></td>
        <td><input type="Checkbox" name="checks" value="{{word.id}}"></td>
    <tr>
        {% endfor %}

        {% endif %}

</table>
{% endblock %}