accounts/urls.py
from django.urls import path

from . import views
from .views import AccountLoginView, activation_email_confirmation
from .views import AccountLogoutView
from .views import AccountRegistrationDoneView
from .views import AccountRegistrationView
from .views import AccountUpdateProfileView
from .views import account_profile_view
from .views import user_activate

app_name = 'accounts'

urlpatterns = [
    path('registration/асtivate/<str:sign>/', user_activate, name='register_activate'),
    path('registration/done/', AccountRegistrationDoneView.as_view(), name='registration_done'),
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_profile_view, name='profile'),
    path('profile_change/', AccountUpdateProfileView.as_view(), name='profile_change'),
    path("mail/", views.send_me_mail),
    path('confirm_email/', activation_email_confirmation, name="activation_email_confirmation")

]

django_learn_helper/urls.py
from django.contrib import admin
from django.urls import path, include
from words import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('words/', include('words.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path('__debug__/', include('debug_toolbar.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

words/urls.py
from django.urls import path
from . import views
from .views import tests_views, words_views, groups_views

app_name = 'words'

urlpatterns = [
    path('list/', words_views.WordsListView.as_view(), name="list"),
    # path('add/', words_views.add_view),
    # path('test/', views.test_view),
    path('', words_views.home_view, name="home"),
    path('<uuid:uuid>/', words_views.one_word_view, name="single"),
    path("create/", words_views.WordCreateView.as_view(), name="create"),
    path("update/<uuid:uuid>/", words_views.WordUpdateView.as_view(), name="update"),
    path("delete/<uuid:uuid>/", words_views.delete_view, name="delete"),
    path("groups/", groups_views.GroupsListView.as_view(), name="groups_list"),
    path("groups/<uuid:uuid>", groups_views.WordsInGroupListView.as_view(), name='group'),
    path("groups/create", groups_views.GroupCreateView.as_view(), name="group_create"),
    path("groups/update/<uuid:uuid>", groups_views.GroupUpdateView.as_view(), name="group_update"),
    path("tests", tests_views.TestsHomeView.as_view(), name="tests_home"),
    # path("tests/quick_test", views.QuickTest.as_view(), name="quick_test"),
    path("tests/groups_of_words_test/<uuid:uuid>", tests_views.GroupOfWordsTest.as_view(), name="groups_of_words_test"),
    path("tests/group_of_words_test/results", tests_views.TestsResultsListView.as_view(), name="test_results"),
    path("tests/group_of_words_test/results/<uuid:uuid>", tests_views.TestsResultView.as_view(), name="single_result")
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Learn Helper</title>
</head>
<body>

{% include "navbar.html" %}
{% block tittle %}
{% endblock %}
{% include 'messages.html' %}
{% block content %}
{% endblock %}

</body>
</html>

templates/index.html
{%extends 'base.html'%}

{%block content%}
    <h1>Welcome to base site page!!!</h1>
    <h1><a href="{% url 'words:home' %}">Words page</a></h1>
{%endblock content%}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<table cellpadding="10">
    <tr>
        <td><img src="{% static 'pictures/default.png' %}" width="50" height="50"></td>
        <td><a href="{% url 'index' %}">Very main page</a></td>

        {% if user.is_authenticated %}
        <td><a href="{% url 'accounts:profile' %}">Profile</a></td>
        <td><a href="{% url 'accounts:logout' %}">Logout</a></td>
        <td><a href="{% url 'password_change' %}">Change password</a></td>
        <td>Welcome, {{user.username}}</td>

        {% else %}
        <td><a href="{% url 'accounts:registration' %}">Registration</a></td>
        <td><a href="{% url 'accounts:login' %}">Login</a></td>


        {% endif %}


    </tr>
</table>



<hr>